import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Header, Content, Chart } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>My portfolio {"<3"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Chart /> */}
        <Header />
        <Content />
      </main>
    </>
  )
}
